---
step_ca_service_name: step-ca
step_ca_service_version: "0.28.3"
step_ca_service_port: "443"
step_ca_data_dir: /var/lib/step-ca
step_ca_config_dir: /etc/step-ca
step_ca_user: step-ca
step_ca_domain: step-ca.local.iamrobertyoung.co.uk
step_ca_container_name: step-ca

step_ca_backup_cron: "*-*-* 04:00:00"
step_ca_backup_image_name: backup-toolkit
step_ca_backup_image_tag: local
step_ca_backup_from: /data
step_ca_backup_mosquitto_host: mosquitto.local.iamrobertyoung.co.uk
step_ca_backup_mosquitto_username: "home-assistant"
step_ca_backup_mosquitto_password: "password"
step_ca_backup_bucket_name: "home-server-backup.iamrobertyoung.co.uk"
