---
- name: Copy dockerfile
  ansible.builtin.copy:
    src: files/dockerfile
    dest: /tmp/Dockerfile
    mode: "0644"
  register: dockerfile_copy

- name: Create backup script
  become: true
  ansible.builtin.copy:
    src: "files/backup.sh"
    dest: "/tmp/backup.sh"
    mode: "0644"
  register: backup_script_copy

- name: Build Docker image
  become: true
  community.docker.docker_image:
    name: "{{ step_ca_backup_image_name }}"
    tag: "{{ step_ca_backup_image_tag }}"
    source: build
    push: false
    build:
      path: /tmp
    force_source: "{{ dockerfile_copy.changed or backup_script_copy.changed }}"
    state: present
  notify: "Restart {{ step_ca_service_name }}"

- name: Create backup .env file
  become: true
  ansible.builtin.template:
    src: templates/docker-compose/backup-toolkit.env.j2
    dest: "{{ step_ca_config_dir }}/backup-toolkit.env"
    group: "{{ step_ca_user }}"
    owner: "{{ step_ca_user }}"
    mode: "0400"
  notify: "Restart {{ step_ca_service_name }}"

- name: Create backup systemd service file for {{ step_ca_service_name }}
  become: true
  ansible.builtin.template:
    src: "templates/backup/backup.service.j2"
    dest: /etc/systemd/system/{{ step_ca_service_name }}-backup.service
    owner: root
    mode: "0644"
  register: backup_service

- name: Create backup systemd timer file for {{ step_ca_service_name }}
  become: true
  ansible.builtin.template:
    src: "templates/backup/backup.timer.j2"
    dest: /etc/systemd/system/{{ step_ca_service_name }}-backup.timer
    owner: root
    mode: "0644"
  register: backup_timer

- name: Reload systemd daemon
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
  when: backup_service.changed or backup_timer.changed

- name: Enable and start backup timer for {{ step_ca_service_name }}
  become: true
  ansible.builtin.systemd:
    name: "{{ step_ca_service_name }}-backup.timer"
    enabled: true
    state: started
