---
- name: Create service user {{ step_ca_user }}
  become: true
  ansible.builtin.user:
    name: "{{ step_ca_user }}"
    create_home: false
    comment: "{{ step_ca_user }} user with no shell access"
    shell: /bin/false
  register: user_result

- name: Create config directory {{ step_ca_config_dir }}
  become: true
  ansible.builtin.file:
    path: "{{ step_ca_config_dir }}"
    state: directory
    mode: "0755"
    owner: "{{ step_ca_user }}"
    group: "{{ step_ca_user }}"

- name: Create data directory {{ step_ca_data_dir }}
  become: true
  ansible.builtin.file:
    path: "{{ step_ca_data_dir }}"
    state: directory
    mode: "0755"
    owner: "{{ step_ca_user }}"
    group: "{{ step_ca_user }}"

- name: Add users to docker group
  become: true
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  with_items:
    - root
    - noxious
    - "{{ step_ca_user }}"
